server :
  port : 8095
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: abc123456

mybatis:
  config : mybatis-config.xml
  mapper-locations: mapper/*Mapper.xml